<a href="https://colab.research.google.com/github/SangMini2/MachineLearning_for_AI/blob/main/week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
filename = "/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02/data/earthquakes.csv"

In [4]:
import pandas as pd

In [39]:
df = pd.read_csv(filename)

In [17]:
df.loc[3:10, ["mag" , "magType", "types"]]

     mag magType                                              types
3   0.44      ml         ,geoserve,nearby-cities,origin,phase-data,
4   2.16      md  ,geoserve,nearby-cities,origin,phase-data,scit...
5   2.61      md                       ,geoserve,origin,phase-data,
6   1.70      ml                                  ,geoserve,origin,
7   1.13      md  ,geoserve,nearby-cities,origin,phase-data,scit...
8   0.92      md  ,geoserve,nearby-cities,origin,phase-data,scit...
9   4.70      mb                       ,geoserve,origin,phase-data,
10  0.50      ml         ,geoserve,nearby-cities,origin,phase-data,

In [20]:
df.loc[df['title'].str.contains('Arizona')]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
1062,NaN,NaN,60300227,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.1666,NaN,163.0,",uu60300227,",1.23,ml,...,",uu,",reviewed,1539133978610,"M 1.2 - 7km SSW of Colorado City, Arizona",0,earthquake,",geoserve,origin,phase-data,",-420.0,1539196068710,https://earthquake.usgs.gov/earthquakes/eventp...
3965,NaN,NaN,60298572,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.1577,NaN,211.0,",uu60298572,",0.94,md,...,",uu,",reviewed,1538383710020,"M 0.9 - 7km WSW of Colorado City, Arizona",0,earthquake,",geoserve,origin,phase-data,",-420.0,1538516934720,https://earthquake.usgs.gov/earthquakes/eventp...

In [18]:
df.sort_values(by="mag", ascending=False).head(10)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
4363,green,2.2,1000h4l1,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.728,1.0,23.0,",at00pfv7ja,us1000h4l1,pt18273000,",6.7,mww,...,",at,us,pt,",reviewed,1538304744240,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake,",dyfi,geoserve,impact-link,losspager,moment-te...",-720.0,1539348741510,https://earthquake.usgs.gov/earthquakes/eventp...
118,green,NaN,1000hbkz,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.623,NaN,25.0,",pt18286001,at00pgjb1a,us1000hbkz,",6.7,mww,...,",pt,at,us,",reviewed,1539429023560,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake,",geoserve,ground-failure,impact-link,losspager...",600.0,1539455437040,https://earthquake.usgs.gov/earthquakes/eventp...
799,green,NaN,1000hacw,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.879,NaN,18.0,",pt18283004,at00pgeomo,us1000hacw,",6.5,mww,...,",pt,at,us,",reviewed,1539213362130,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake,",geoserve,ground-failure,impact-link,losspager...",600.0,1539224915040,https://earthquake.usgs.gov/earthquakes/eventp...
816,green,NaN,1000habl,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.907,NaN,12.0,",us1000habl,",6.2,mww,...,",us,",reviewed,1539208835130,"M 6.2 - 94km SW of Kokopo, Papua New Guinea",1,earthquake,",geoserve,ground-failure,losspager,moment-tens...",600.0,1539219109963,https://earthquake.usgs.gov/earthquakes/eventp...
838,green,NaN,1000ha9t,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.757,NaN,18.0,",us1000ha9t,",6.1,mb,...,",us,",reviewed,1539204326420,"M 6.1 - 132km E of Kimbe, Papua New Guinea",1,earthquake,",geoserve,ground-failure,losspager,origin,phas...",600.0,1539217505598,https://earthquake.usgs.gov/earthquakes/eventp...
5323,green,NaN,1000h3mf,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.812,NaN,33.0,",us1000h3mf,",6.1,mww,...,",us,",reviewed,1538118001950,"M 6.1 - 55km NNW of Palu, Indonesia",1,earthquake,",geoserve,ground-failure,losspager,moment-tens...",480.0,1538158590933,https://earthquake.usgs.gov/earthquakes/eventp...
9211,green,NaN,2000hg93,https://earthquake.usgs.gov/fdsnws/event/1/que...,8.749,NaN,22.0,",us2000hg93,",6.0,mww,...,",us,",reviewed,1537255661330,M 6.0 - Southwest Indian Ridge,0,earthquake,",geoserve,losspager,moment-tensor,origin,phase...",180.0,1538206958458,https://earthquake.usgs.gov/earthquakes/eventp...
862,green,4.3,1000ha6q,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.051,170.0,27.0,",us1000ha6q,",6.0,mww,...,",us,",reviewed,1539197095310,"M 6.0 - 39km NNE of Sumberanyar, Indonesia",0,earthquake,",dyfi,geoserve,ground-failure,losspager,moment...",480.0,1539515759040,https://earthquake.usgs.gov/earthquakes/eventp...

In [23]:
df.drop("alert",axis = 1, inplace = True) #axis=1 : 열 데이터 삭제, axis=0 : 행 데이터 삭제

In [40]:
mag = df.pop("mag")
magType = df.pop("magType")

In [42]:
new_df = pd.concat([mag,magType], axis = 1 ) #axis=1 은 좌우로 데이터 합치는 것

In [43]:
new_df

       mag magType
0     1.35      ml
1     1.29      ml
2     3.42      ml
3     0.44      ml
4     2.16      md
...    ...     ...
9327  0.62      md
9328  1.00      ml
9329  2.40      md
9330  1.10      ml
9331  0.66      ml

[9332 rows x 2 columns]

ch3. Codes Practice

In [44]:
#head func
new_df.head(3)

    mag magType
0  1.35      ml
1  1.29      ml
2  3.42      ml